name: sbm_custom
remove_h: null
# datadir: 'data/sbm_custom128_32_40/'
# num_graphs: '128_32_40'

datadir: 'data/sbm_custom128x1_32_40_l6_flexible_num_nodes/'
num_graphs: 'sbm_custom128x1_32_40_l6_flexible_num_nodes'

multilabel: True
post_processing: null
# post_processing:
#   max_clique_size: 5

data_augmentation: false
# The proportion of the dataset to re-project at every epoch. 
# To re-project all the dataset every time, set this parameter to None.
change_rate: 0.5  

samples_per_epoch: 128
num_layers: 6

# clique_loss_coef: [0., 0.]
clique_loss_coef: null
model_type: 'MultiLayerXEyTransformer'

baseline:
  node_degree_wasserstein:
    HYGENE: 0.321
    HyperPLR: 0.661
  edge_size_wasserstein:
    HYGENE: 0.002
    HyperPLR: 0.0
  spectral:
    HYGENE: 0.010
    HyperPLR: 0.016
  is_sbm:
    HYGENE: 0.65
    HyperPLR: 0.0
  centrality_closeness:
    HYGENE: 0.016
  centrality_betweenness:
    HYGENE: 4.4e-4
  centrality_harmonic:
    HYGENE: 2.990
  