defaults:
    - _self_
    - general : general_erdos_test
    - model : model_erdos_test
    # - model : discrete
    - train : train_erdos_test
    # - augmentation_train : augment_sbm
    - dataset : erdos_test
    # - tuning : tuning_default

hydra:
  job:
    chdir: True
  run:
    dir: ../outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${general.name}
    