# Training settings
# n_epochs: 5000
n_epochs: 25000
# n_epochs: 25
# n_epochs: 10 # for debug
# batch_size: 40  # for triplet attention
batch_size: 26
lr: 0.0002
# lr: 0.00001
clip_grad: 1.0          # float, null to disable
save_model: True
num_workers: 0
ema_decay: 0.999          # 'Amount of EMA decay, 0 means off. A reasonable value  is 0.999.'
progress_bar: true
weight_decay: 1e-12
# optimizer: adamw # adamw,nadamw,nadam => nadamw for large batches, see http://arxiv.org/abs/2102.06356 for the use of nesterov momentum with large batches
optimizer: nadamw
scheduler: null

seed: 0
display_memory_summary: false

weight_BCE: 1.0